
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Dome Shades
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.domeshades.com/
#
# 2. URL of this page
url:              http://ajreagan.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Dome Shades
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://igg.me/dome-shades
  #
  # URL of a cover photo of your project
  cover_image:    http://static.wixstatic.com/media/b11e60_7416a5fc41a5d30b8b458bbe6c23b90f.jpg
  #
  # Use a one-liner to describe your project
  description:    Dome Shades are quality sunglasses designed for big heads
#
# 4. Your Twitter handle
twitter_handle:   DomeShades
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  What's up everyone?<br />
  First of all, thank you for visiting our site<br />
 Secondly, I hope you're having an awesome day. You're here because you have influence. When you share something, people pay attention. So, please take a few seconds to spread the Dome love.
